---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jod
  labels:
    app.kubernetes.io/name: jod
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: jod
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jod
    spec:
      containers:
        - name: jod
          image: jod
          env:
            - name: GOWON_BROKER
              value: mosquitto:1883
